Update install-desktop

diff --git a/scripts/install-desktop b/scripts/install-desktop
--- a/scripts/install-desktop
+++ b/scripts/install-desktop
@@ -174,8 +174,8 @@ then
         apt-get install -y hdf-compass || fail
         apt-get install -y stacer gnome-system-monitor || fail
     else
-        add-apt-repository -y ppa:nomacs/stable || fail
-        add-apt-repository -y ppa:notepadqq-team/notepadqq || fail
+        #add-apt-repository -y ppa:nomacs/stable || fail
+        #add-apt-repository -y ppa:notepadqq-team/notepadqq || fail
         add-apt-repository -y ppa:oguzhaninan/stacer || fail
         if [ -d "/var/cache/app-info/xapian/default" ]; then
             chmod -R a+rX,u+w /var/cache/app-info/xapian/default || fail
@@ -185,7 +185,7 @@ then
         apt-get install -y vim-gnome notepadqq nomacs stacer gnome-system-monitor || fail
     fi
 
-    if [ "x${UBUNTU_VER}" = "xbionic" ]
+    if [ "x${UBUNTU_VER}" = "xbionic" ] || [ "x${UBUNTU_VER}" = "xjammy" ]
     then
         apt-get install -y hdf-compass || fail
     fi
@@ -222,13 +222,13 @@ then
     # bash /root/scripts/install-desktop-exts MODE=vscode USER_ROOT=${USER_ROOT} || fail
 
     # Install PeaZip.
-    if [ "x${UBUNTU_VER}" = "xfocal" ] || [ "x${UBUNTU_VER}" = "xbionic" ]
-    then
-        wget https://github.com/peazip/PeaZip/releases/download/9.0.0/peazip_9.0.0.LINUX.GTK2-1_amd64.deb -O peazip.deb || fail        
-    else
-        wget https://github.com/peazip/PeaZip/releases/download/6.6.0/peazip_6.6.0.LINUX.GTK2-2_i386.deb -O peazip.deb || fail
-    fi
-    apt-get -y install ./peazip.deb || fail && rm -f peazip.deb || fail
+    if [ "x${UBUNTU_VER}" = "xfocal" ] || [ "x${UBUNTU_VER}" = "xbionic" ]; then    
+        wget https://github.com/peazip/PeaZip/releases/download/9.0.0/peazip_9.0.0.LINUX.GTK2-1_amd64.deb -O peazip.deb || fail  
+        apt-get -y install ./peazip.deb || fail && rm -f peazip.deb || fail
+    if [ "x${UBUNTU_VER}" = "xxenial" ]; then
+        wget https://github.com/peazip/PeaZip/releases/download/6.6.0/peazip_6.6.0.LINUX.GTK2-2_i386.deb -O peazip.deb || fail   
+        apt-get -y install ./peazip.deb || fail && rm -f peazip.deb || fail
+    fi    
 
     # Install GitFiend 
     wget -O gitfiend.deb https://github.com/cainmagi/Dockerfiles/releases/download/xubuntu-v1.7-u20.04/GitFiend_0.38.3_amd64.deb || fail
