Update install-desktop

diff --git a/scripts/install-desktop b/scripts/install-desktop
--- a/scripts/install-desktop
+++ b/scripts/install-desktop
@@ -68,7 +68,7 @@ then
     apt-get install -y xubuntu-desktop synaptic language-selector-gnome || fail
     apt-get install -y xfce4 || fail
     # Install the xfce4 addons
-    if [ "x${UBUNTU_VER}" = "xfocal" ]
+    if [ "x${UBUNTU_VER}" = "xfocal" ] || [ "x${UBUNTU_VER}" = "xjammy" ]
     then
         # Install libgtk
         apt-get install -y libgtk-3-bin libgtk2.0-bin libgtk-3-dev libgtk2.0-dev libgirepository1.0-dev \
@@ -101,12 +101,12 @@ then
         apt-get install -y xfce4-notifyd mousepad xfce4-terminal \
             xfce4-taskmanager lightdm-gtk-greeter-settings || fail
         # Install xfce-plugin
-        apt-get install -y xfce4-battery-plugin xfce4-settings xfce4-clipman-plugin \
-            xfce4-cpugraph-plugin xfce4-datetime-plugin xfce4-netload-plugin \
-            xfce4-notes-plugin xfce4-places-plugin xfce4-sensors-plugin \
-            xfce4-systemload-plugin xfce4-mailwatch-plugin xfce4-cpufreq-plugin \
-            xfce4-diskperf-plugin xfce4-fsguard-plugin \            
-            xfce4-appfinder xfce4-dict terminator || fail
+        #apt-get install -y xfce4-battery-plugin xfce4-settings xfce4-clipman-plugin \
+            #xfce4-cpugraph-plugin xfce4-datetime-plugin xfce4-netload-plugin \
+            #xfce4-notes-plugin xfce4-places-plugin xfce4-sensors-plugin \
+            #xfce4-systemload-plugin xfce4-mailwatch-plugin xfce4-cpufreq-plugin \
+            #xfce4-diskperf-plugin xfce4-fsguard-plugin \            
+            #xfce4-appfinder xfce4-dict terminator || fail
         # Install screen saver
         apt-get install -y xscreensaver xscreensaver-gl-extra xscreensaver-data-extra \
             xscreensaver-screensaver-bsod || fail
@@ -133,7 +133,7 @@ then
     UBUNTU_VER=$(lsb_release -cs)
 
     # Install Chrome
-    if [ "x${UBUNTU_VER}" = "xfocal" ]
+    if [ "x${UBUNTU_VER}" = "xfocal" ] || [ "x${UBUNTU_VER}" = "xjammy" ]
     then
         wget -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb || fail
         apt-get install -y ./google-chrome.deb || fail
@@ -154,7 +154,7 @@ then
     fi
 
     # Install evince.
-    if [ "x${UBUNTU_VER}" = "xfocal" ]
+    if [ "x${UBUNTU_VER}" = "xfocal" ] || [ "x${UBUNTU_VER}" = "xjammy" ]
     then
         apt-get install -y evince evince-common poppler-data || fail
     else
@@ -167,7 +167,7 @@ then
     fi
 
     # Install apps provided in Ubuntu 20.04. In ealier OS, we need to add some ppas.
-    if [ "x${UBUNTU_VER}" = "xfocal" ]
+    if [ "x${UBUNTU_VER}" = "xfocal" ] || [ "x${UBUNTU_VER}" = "xjammy" ]
     then
         apt-get install -y vim-gtk3 vim-gui-common kate || fail
         apt-get install -y nomacs nomacs-l10n || fail
@@ -194,7 +194,7 @@ then
     wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg || fail
     install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/ || fail
     sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list' || fail
-    if [ "x${UBUNTU_VER}" = "xfocal" ]
+    if [ "x${UBUNTU_VER}" = "xfocal" ] || [ "x${UBUNTU_VER}" = "xjammy" ]
     then
         sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list' || fail
     fi
@@ -207,7 +207,7 @@ then
         chmod -R a+rX,u+w /var/cache/app-info/xapian/default || fail
     fi
     apt-get update -y || fail && apt-get -y dist-upgrade || fail
-    if [ "x${UBUNTU_VER}" = "xfocal" ]
+    if [ "x${UBUNTU_VER}" = "xfocal" ] || [ "x${UBUNTU_VER}" = "xjammy" ]
     then
         apt-get install -y code microsoft-edge-stable || fail
     else
@@ -259,7 +259,7 @@ then
     apt-get install -y at-spi2-core || fail
 
     # Install fcitx5 if in Ubuntu 20.04.
-    if [ "x${UBUNTU_VER}" = "xfocal" ]; then
+    if [ "x${UBUNTU_VER}" = "xfocal" ] || [ "x${UBUNTU_VER}" = "xjammy" ]; then
         add-apt-repository -y ppa:zhsj/fcitx5 || fail
         apt-get update -qq || fail
         apt-get install -y fcitx5 fcitx5-chinese-addons fcitx5-data fcitx5-frontend-gtk2 fcitx5-frontend-gtk3 fcitx5-frontend-qt5 fcitx5-module-cloudpinyin fcitx5-module-fullwidth fcitx5-module-pinyinhelper fcitx5-module-punctuation fcitx5-module-quickphrase fcitx5-module-quickphrase-editor fcitx5-modules fcitx5-pinyin gir1.2-fcitxg-1.0 fcitx5-module-lua fcitx5-material-color fcitx5-rime kde-config-fcitx5 || fail
