Update install-desktop

diff --git a/scripts/install-desktop b/scripts/install-desktop
--- a/scripts/install-desktop
+++ b/scripts/install-desktop
@@ -293,18 +293,27 @@ then
     # Install Python/Pip.
     if [ "x${CUR_PY_VER}" == "xpy37+" ]
     then
-        if [ "x${UBUNTU_VER}" = "xjammy" ]; then
-            apt install -y python3-pip || fail
+        if [ "x${USE_CURL}" == "x1" ]
+        then
+            curl https://bootstrap.pypa.io/pip/get-pip.py -o /root/scripts/get-pip-3.py || fail
         else
-            msg "pip is not installed, use get-pip.py to install it"
-            if [ "x${USE_CURL}" == "x1" ]; then
-                curl https://bootstrap.pypa.io/get-pip.py -o /root/scripts/get-pip.py || fail
-            else
-                wget -O /root/scripts/get-pip.py https://bootstrap.pypa.io/get-pip.py || fail
-            fi
-            python3 /root/scripts/get-pip.py || fail
+            wget -O /root/scripts/get-pip-3.py https://bootstrap.pypa.io/pip/get-pip.py || fail
         fi
     fi
+    #if [ "x${CUR_PY_VER}" == "xpy37+" ]
+    #then
+        #if [ "x${UBUNTU_VER}" = "xjammy" ]; then
+            #apt install -y python3-pip || fail
+        #else
+            #msg "pip is not installed, use get-pip.py to install it"
+            #if [ "x${USE_CURL}" == "x1" ]; then
+                #curl https://bootstrap.pypa.io/get-pip.py -o /root/scripts/get-pip.py || fail
+            #else
+                #wget -O /root/scripts/get-pip.py https://bootstrap.pypa.io/get-pip.py || fail
+           # fi
+            #python3 /root/scripts/get-pip.py || fail
+        #fi
+    #fi
     if [ "x${CUR_PY_VER}" == "xpy36" ]
     then
         if [ "x${USE_CURL}" == "x1" ]
